### ISSUE TITLE
internal server error when trying to upload file

### ISSUE THREAD

**Issue by BayoKwendo** [hviana/Upload-middleware-for-Oak-Deno-framework#16]
[uncaught oak error]: TypeError - Cannot read property 'body' of undefined

request: { url: "http://localhost:2021/upload", method: "POST", hasBody: true }
response: { status: 404, type: undefined, hasBody: false, writable: true }

    at https://deno.land/x/oak_upload_middleware@3.0/mod.ts:53:39
    at dispatch (https://deno.land/x/oak@v8.0.0/middleware.ts:41:13)
    at https://deno.land/x/oak@v8.0.0/router.ts:986:20
    at dispatch (https://deno.land/x/oak@v8.0.0/middleware.ts:41:13)
    at composedMiddleware (https://deno.land/x/oak@v8.0.0/middleware.ts:44:12)
    at dispatch (https://deno.land/x/oak@v8.0.0/router.ts:992:28)
    at dispatch (https://deno.land/x/oak@v8.0.0/middleware.ts:41:13)
    at allowedMethods (https://deno.land/x/oak@v8.0.0/router.ts:582:13)
    at dispatch (https://deno.land/x/oak@v8.0.0/middleware.ts:41:13)
    at dispatch (https://deno.land/x/oak@v8.0.0/router.ts:972:34)

How can i sort this. deno 1.12.1
typescript 4.3.5

**Comment by spawnia** [comment]
Fixed by https://github.com/hviana/Upload-middleware-for-Oak-Deno-framework/pull/17
